In [1]:
%load_ext autoreload
%autoreload 2

env = None

## Import policy and env

In [2]:
from IPython.display import Video

import os
import numpy as np
import json
import pybullet as p
import imageio

from PIL import Image
from rrc_example_package.viz_utils import VisualMarkers
from rrc_example_package.pd_control import PDControlPolicy
from rrc_example_package.cube_trajectory_env import ActionType, SimCubeTrajectoryEnv

# comment if running remote with VNC
os.environ["DISPLAY"] = ":1"

pybullet build time: Dec 23 2020 01:48:06


ROS not imported, testing mode
ROS not imported, testing mode


## Helper funcs

In [3]:
import os
import pybullet as p
import glob
from PIL import Image


def get_vid_path():
    i = 0
    vid_path = lambda: f'vids/run{i}.mp4'
    if not os.path.exists(os.path.split(vid_path())[0]):
        os.makedirs(os.path.split(vid_path())[0])
    while os.path.exists(vid_path()):
        i += 1
    return vid_path()


def write_frame_to_image(img_path, **camera_kwargs):
    frame = p.getCameraImage(**camera_kwargs)[2]
    im = Image.fromarray(frame)
    im.save(img_path)
    return


def write_frames_to_video(frames=None, img_dir="", fps=20):
    if img_dir:
        frames = sorted(glob.glob(os.path.join(img_dir, "img*.png")),
                        key=lambda x: int(x.split("img")[1].split(".")[0]))
    vid_path = get_vid_path()
    writer = imageio.get_writer(vid_path, fps=20)  # actual fps is 1000 // save_freq ~~ 200
    for image in frames:
        if img_dir:
            image = imageio.imread(file)
        writer.append_data(image)
    writer.close()
    print(f"wrote frames to {vid_path}")
    return vid_path


def debug_markers(markers, grasp_pts, marker_colors=None):
    # default to RGB
    if marker_colors is None:
        marker_colors = [(1., 0., 0., .5), 
                         (0., 1., 0., .5), 
                         (0., 0., 1., .5)]
    if markers is None:
        markers = VisualMarkers()
        for grasp_pt, color in zip(grasp_pts, marker_colors):
            markers.add(grasp_pt, color=color)
    else:
        for marker, grasp_pt in zip(markers.markers, grasp_pts):
            marker.set_state(grasp_pt)
    return markers


def load_debug_camera_viz_configs(config_path='debug_camera.npz'):
    """Loads debug camera and visualizer kwargs"""
    debug_camera_kwargs = dict(np.load(config_path))
    visualizer_kws = ['cameraDistance', 'cameraYaw', 'cameraPitch', 'cameraTargetPosition']
    camera_kws = ['width', 'height', 'viewMatrix', 'projectionMatrix']
    scalar_kws = ['width', 'height', 'cameraYaw', 'cameraPitch', 'cameraDistance']
    for k in scalar_kws:
        debug_camera_kwargs[k] = debug_camera_kwargs[k].item()

    debug_camera_kwargs['width'] = debug_camera_kwargs['width'] // 4
    debug_camera_kwargs['height'] = debug_camera_kwargs['height'] // 4

    camera_kwargs = {k: debug_camera_kwargs[k] for k in camera_kws}
    visualizer_kwargs = {k: debug_camera_kwargs[k] for k in visualizer_kws}
    return camera_kwargs, visualizer_kwargs


def calc_gravity(observation, inv_dyn=False):
    q0 = observation['robot_observation']['position']
    dq0 = observation['robot_observation']['velocity']
    if inv_dyn:
        return np.asarray(p.calculateInverseDynamics(
            env.platform.simfinger.finger_id,
            list(q0), list(dq0),
            [0.0 for _ in range(9)]
        ))

    jac_g = 0
    for fid in range(3):
        frame_ids = [
                policy.kinematics.finger_link_ids[f'finger_{link}_link_{fid * 120}'] + 2
                    for link in ['upper', 'middle', 'lower']]
        frame_names = [policy.kinematics.robot_model.frames[i].name for i in frame_ids]
        # print(frame_names)
        ms = policy.kinematics.ms
        for i, frame_id in enumerate(frame_ids):
            grav = np.array([0, 0, -9.8 * ms[i]])
            jac_g -= policy.kinematics.compute_jacobian(frame_id, q0)[:3,:].T @ grav

    return jac_g

## Run episode boilerplate

Close and delete env and policy
```python
env.close()
del env
del policy
```

Camera visualization params

```python
(width,
height,
viewMatrix,
projectionMatrix,
cameraUp,
cameraForward,
horizontal,
vertical,
cameraYaw,
cameraPitch,
cameraDistance,
target) = p.getDebugVisualizerCamera()

np.savez('debug_camera.npz', width=width, height=height,
         viewMatrix=viewMatrix, projectionMatrix=projectionMatrix,
         cameraYaw=cameraYaw, cameraPitch=cameraPitch, 
         cameraDistance=cameraDistance, cameraTargetPosition=target)
```

Load pinocchio utils from benchmark-rrc

```python
from rrc.env import pinocchio_utils
import os.path as osp
import trifinger_simulation

robot_properties_path = osp.join(osp.split(osp.abspath(trifinger_simulation.__file__))[0],
                                         "robot_properties_fingers")
urdf_file = trifinger_simulation.finger_types_data.get_finger_urdf(
    "trifingerpro"
)
finger_urdf_path = osp.join(robot_properties_path, "urdf", urdf_file)
pi = pinocchio_utils.PinocchioUtils(finger_urdf_path)
pi.compute_jacobian = pi.get_any_link_jacobian
pi.compute_lambda_and_g_matrix = pi.get_lambda_and_g_matrix
```

## Initialize policy and env

In [4]:
# initialize visualization vars
save_vid = False
save_freq = 10
visualization = True

camera_kwargs, visualizer_kwargs = load_debug_camera_viz_configs()

# load goal
goal_json = './goal.json'
goal = json.loads(open(goal_json, "r").read())["_goal"]

# create env
if env is None:
    env = SimCubeTrajectoryEnv(
        goal_trajectory=goal,  # passing None to sample a random trajectory
        action_type=ActionType.TORQUE,
        visualization=visualization,
    )

# initialize loop vars and visualizer (if visualization==True)
is_done = False
observation = env.reset()
p.resetDebugVisualizerCamera(**visualizer_kwargs)
p.configureDebugVisualizer(p.COV_ENABLE_GUI, 0)

t = 0

# create policy
policy = PDControlPolicy(env.action_space, env.info["trajectory"])

## Computing gravity compensation forces

```python
import time
q0 = observation['robot_observation']['position']
dq0 = observation['robot_observation']['velocity']
g2 = np.asarray(p.calculateInverseDynamics(
    env.platform.simfinger.finger_id,
    list(q0), list(dq0),
    [0.0 for _ in range(9)]
))

g_tot = 0
for fid in [0,120,240]:
    frame_ids = [policy.kinematics.finger_link_ids[f'finger_{link}_link_{fid}'] + 1 for link in ['upper', 'middle', 'lower']]
    ms = policy.kinematics.ms
    for i, frame_id in enumerate(frame_ids):
        grav = np.array([0, 0, -9.8 * ms[i]]) 
        g_tot -= policy.kinematics.compute_jacobian(frame_id, q0)[:3,:].T @ grav
```

In [5]:
from rrc_example_package import utils

# first write after reset
is_done = False
observation = env.reset()
p.resetDebugVisualizerCamera(**visualizer_kwargs)
t = 0

markers = None
last_mode = ""

q0 = observation['robot_observation']['position']
dq0 = observation['robot_observation']['velocity']
inv_dyn_g = np.asarray(p.calculateInverseDynamics(
    env.platform.simfinger.finger_id,
    list(q0), list(dq0),
    [0.0 for _ in range(9)]
))


while not is_done:
    action = policy.predict(observation, t=10)  # always on off mode
    gravity_comp = calc_gravity(observation, inv_dyn=False)
    observation, reward, is_done, info = env.step(gravity_comp)
    t = info["time_index"]
    grasp_pts, normals = policy.compute_grasp_points_normals(observation, overwrite_z=True)
    if policy.set_mode(t) != last_mode:
        last_mode = policy.set_mode(t)
        if (~np.isclose(grasp_pts[:, 2], utils.CUBE_HALF_SIZE, atol=1e-6)).any():
            print(grasp_pts[:, 2] - utils.CUBE_HALF_SIZE)
            pdb.set_trace()
        markers = debug_markers(markers, grasp_pts)
        for m in markers.markers:
            print(m.position)
    if save_vid and t % save_freq == 0:
        write_frame_to_image(f"/tmp/img{t}.png", **camera_kwargs)

if save_vid:
    write_frames_to_video(img_dir="/tmp")

[0.     0.0335 0.0335]
[ 0.     -0.0335  0.0335]
[-0.0335  0.      0.0335]
[-0.00225968  0.0356272   0.0335    ]
[-0.00117943 -0.03136409  0.0335    ]
[-0.0352152   0.00159143  0.0335    ]
[-0.00225594  0.03562741  0.0335    ]
[-0.00118031 -0.03136395  0.0335    ]
[-0.03521381  0.00159392  0.0335    ]
[-0.00225749  0.03563043  0.0335    ]
[-0.00118596 -0.031361    0.0335    ]
[-0.03521744  0.00159895  0.0335    ]


## Running episode with PDControl Policy

In [58]:
# first write after reset
if save_vid:
    write_frame_to_image(f"/tmp/img{t}.png", **camera_kwargs)

markers = None
last_mode = ""

while not is_done:
    action = policy.predict(observation, t)  # always on off mode
    observation, reward, is_done, info = env.step(action)
    t = info["time_index"]
    grasp_pts, normals = policy.compute_grasp_points_normals(observation, overwrite_z=True)
    if policy.set_mode(t) != last_mode:
        last_mode = policy.set_mode(t)
        if (~np.isclose(grasp_pts[:, 2], utils.CUBE_HALF_SIZE, atol=1e-6)).any():
            print(grasp_pts[:, 2] - utils.CUBE_HALF_SIZE)
            pdb.set_trace()
        markers = debug_markers(markers, grasp_pts)
    if save_vid and t % save_freq == 0:
        write_frame_to_image(f"/tmp/img{t}.png", **camera_kwargs)

if save_vid:
    write_frames_to_video(img_dir="/tmp")

100 off
200 off
300 off
400 off
500 safe
600 safe
700 safe
800 safe
900 safe
1000 pos
1100 pos
1200 pos
1300 pos
1400 pos
1500 pos
1600 pos
1700 pos
1800 pos
1900 pos


2000 up
Failed to solve!
F.value:  None
positions:  [[ 3.81823749e-02  9.08385352e-05  4.30713156e-02]
 [ 5.91806361e-03 -4.47746470e-02  1.84331054e-02]
 [-4.43961836e-02  2.45946482e-03  1.75933925e-02]]
normals:  [[ 8.96686038e-02  9.95971657e-01 -8.18075197e-06]
 [-8.96686038e-02 -9.95971657e-01  8.18075197e-06]
 [-9.95971657e-01  8.96686036e-02 -9.32499352e-06]]
target_force:  [ 1.85888369e-04 -2.68157883e-04  7.93301992e-01]
target_torque:  [3.51617436e-06 3.50164058e-06 1.79578407e-02]


AttributeError: 'PDControlPolicy' object has no attribute 'previous_global_forces'

In [48]:
grasp_pts[:, 2], utils.CUBE_HALF_SIZE

(array([0.0325, 0.0325, 0.0325]), 0.0335)

In [15]:
[p.getBodyInfo(x.body_id) for x in markers.markers]

[(b'link0', b''), (b'link0', b''), (b'link0', b'')]

In [38]:
import matplotlib.pyplot as plt

yzs = np.concatenate([gp[:, 1:] for gp in grasp_pt_hist])
xzs = np.concatenate([gp[:, [0,2]] for gp in grasp_pt_hist])

f, ax = plt.subplots(ncols=2, figsize=(12,6))
ax[0].scatter(yzs[:, 0], yzs[:, 1])
ax[1].scatter(xzs[:, 0], xzs[:, 1])

ValueError: need at least one array to concatenate

In [59]:
action

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
if save_vid:
    write_frames_to_video(frames)

wrote frames to vids/run0.mp4


In [44]:

Video("vids/run0.mp4")