In [1]:
%load_ext autoreload
%autoreload 2

env = None

## Import policy and env

In [8]:
from IPython.display import Video

import os
import numpy as np
import json
import pybullet as p
import imageio

from PIL import Image
from nerf_rrc import utils
from nerf_rrc.viz_utils import VisualMarkers
from nerf_rrc.pd_control import PDControlPolicy
from nerf_rrc.cube_trajectory_env import ActionType, SimCubeTrajectoryEnv
from nerf_grasping.control import pos_control

# comment if running remote with VNC
os.environ["DISPLAY"] = ":1"

## Helper funcs

In [3]:
import os
import pybullet as p
import glob
from PIL import Image


def get_vid_path():
    i = 0
    vid_path = lambda: f'vids/run{i}.mp4'
    if not os.path.exists(os.path.split(vid_path())[0]):
        os.makedirs(os.path.split(vid_path())[0])
    while os.path.exists(vid_path()):
        i += 1
    return vid_path()


def write_frame_to_image(img_path, **camera_kwargs):
    frame = p.getCameraImage(**camera_kwargs)[2]
    im = Image.fromarray(frame)
    im.save(img_path)
    return


def write_frames_to_video(frames=None, img_dir="", fps=20):
    if img_dir:
        frames = sorted(glob.glob(os.path.join(img_dir, "img*.png")),
                        key=lambda x: int(x.split("img")[1].split(".")[0]))
    vid_path = get_vid_path()
    writer = imageio.get_writer(vid_path, fps=20)  # actual fps is 1000 // save_freq ~~ 200
    for image in frames:
        if img_dir:
            image = imageio.imread(file)
        writer.append_data(image)
    writer.close()
    print(f"wrote frames to {vid_path}")
    return vid_path


def debug_markers(markers, grasp_pts, marker_colors=None):
    # default to RGB
    if marker_colors is None:
        marker_colors = [(1., 0., 0., .5), 
                         (0., 1., 0., .5), 
                         (0., 0., 1., .5)]
    if markers is None:
        markers = VisualMarkers()
        for grasp_pt, color in zip(grasp_pts, marker_colors):
            markers.add(grasp_pt, color=color)
    else:
        for marker, grasp_pt in zip(markers.markers, grasp_pts):
            marker.set_state(grasp_pt)
    return markers


def load_debug_camera_viz_configs(config_path='./nerf_rrc/debug_camera.npz'):
    """Loads debug camera and visualizer kwargs"""
    debug_camera_kwargs = dict(np.load(config_path))
    visualizer_kws = ['cameraDistance', 'cameraYaw', 'cameraPitch', 'cameraTargetPosition']
    camera_kws = ['width', 'height', 'viewMatrix', 'projectionMatrix']
    scalar_kws = ['width', 'height', 'cameraYaw', 'cameraPitch', 'cameraDistance']
    for k in scalar_kws:
        debug_camera_kwargs[k] = debug_camera_kwargs[k].item()

    debug_camera_kwargs['width'] = debug_camera_kwargs['width'] // 4
    debug_camera_kwargs['height'] = debug_camera_kwargs['height'] // 4

    camera_kwargs = {k: debug_camera_kwargs[k] for k in camera_kws}
    visualizer_kwargs = {k: debug_camera_kwargs[k] for k in visualizer_kws}
    return camera_kwargs, visualizer_kwargs


def calc_gravity(observation, inv_dyn=False):
    q0 = observation['robot_observation']['position']
    dq0 = observation['robot_observation']['velocity']
    if inv_dyn:
        return np.asarray(p.calculateInverseDynamics(
            env.platform.simfinger.finger_id,
            list(q0), list(dq0),
            [0.0 for _ in range(9)]
        ))

    jac_g = 0
    for fid in range(3):
        frame_ids = [
                policy.kinematics.finger_link_ids[f'finger_{link}_link_{fid * 120}'] + 2
                    for link in ['upper', 'middle', 'lower']]
        frame_names = [policy.kinematics.robot_model.frames[i].name for i in frame_ids]
        print(frame_names)
        ms = policy.kinematics.ms
        for i, frame_id in enumerate(frame_ids):
            grav = np.array([0, 0, -9.8 * ms[i]])
            jac_g -= policy.kinematics.compute_jacobian(frame_id, q0)[:3,:].T @ grav

    return jac_g

## Run episode boilerplate

Close and delete env and policy
```python
env.close()
del env
del policy
```

Camera visualization params

```python
(width,
height,
viewMatrix,
projectionMatrix,
cameraUp,
cameraForward,
horizontal,
vertical,
cameraYaw,
cameraPitch,
cameraDistance,
target) = p.getDebugVisualizerCamera()

np.savez('debug_camera.npz', width=width, height=height,
         viewMatrix=viewMatrix, projectionMatrix=projectionMatrix,
         cameraYaw=cameraYaw, cameraPitch=cameraPitch, 
         cameraDistance=cameraDistance, cameraTargetPosition=target)
```

Load pinocchio utils from benchmark-rrc

```python
from rrc.env import pinocchio_utils
import os.path as osp
import trifinger_simulation

robot_properties_path = osp.join(osp.split(osp.abspath(trifinger_simulation.__file__))[0],
                                         "robot_properties_fingers")
urdf_file = trifinger_simulation.finger_types_data.get_finger_urdf(
    "trifingerpro"
)
finger_urdf_path = osp.join(robot_properties_path, "urdf", urdf_file)
pi = pinocchio_utils.PinocchioUtils(finger_urdf_path)
pi.compute_jacobian = pi.get_any_link_jacobian
pi.compute_lambda_and_g_matrix = pi.get_lambda_and_g_matrix
```

## Initialize policy and env

In [4]:
# initialize visualization vars
save_vid = False
save_freq = 10
visualization = True

camera_kwargs, visualizer_kwargs = load_debug_camera_viz_configs()

# load goal
goal_json = './goal.json'
goal = json.loads(open(goal_json, "r").read())["_goal"]

# create env
if env is None:
    env = SimCubeTrajectoryEnv(
        goal_trajectory=goal,  # passing None to sample a random trajectory
        action_type=ActionType.TORQUE,
        visualization=visualization,
    )

# initialize loop vars and visualizer (if visualization==True)
is_done = False
observation = env.reset()
p.resetDebugVisualizerCamera(**visualizer_kwargs)
p.configureDebugVisualizer(p.COV_ENABLE_GUI, 0)

t = 0

# create policy
policy = PDControlPolicy(env.action_space, env.info["trajectory"])

## Computing gravity compensation forces

```python
import time
q0 = observation['robot_observation']['position']
dq0 = observation['robot_observation']['velocity']
g2 = np.asarray(p.calculateInverseDynamics(
    env.platform.simfinger.finger_id,
    list(q0), list(dq0),
    [0.0 for _ in range(9)]
))

g_tot = 0
for fid in [0,120,240]:
    frame_ids = [policy.kinematics.finger_link_ids[f'finger_{link}_link_{fid}'] + 1 for link in ['upper', 'middle', 'lower']]
    ms = policy.kinematics.ms
    for i, frame_id in enumerate(frame_ids):
        grav = np.array([0, 0, -9.8 * ms[i]]) 
        g_tot -= policy.kinematics.compute_jacobian(frame_id, q0)[:3,:].T @ grav
```

In [5]:
calc_gravity(observation)

['finger_middle_link_0', 'finger_lower_link_0', 'finger_tip_link_0']
['finger_middle_link_120', 'finger_lower_link_120', 'finger_tip_link_120']
['finger_middle_link_240', 'finger_lower_link_240', 'finger_tip_link_240']


array([-0.26935934,  0.33939203, -0.06264092, -0.26935934,  0.33939203,
       -0.06264092, -0.26935934,  0.33939203, -0.06264092])

In [6]:
# first write after reset
is_done = False
observation = env.reset()
p.resetDebugVisualizerCamera(**visualizer_kwargs)
t = 0

markers = None
last_mode = ""

q0 = observation['robot_observation']['position']
dq0 = observation['robot_observation']['velocity']
inv_dyn_g = np.asarray(p.calculateInverseDynamics(
    env.platform.simfinger.finger_id,
    list(q0), list(dq0),
    [0.0 for _ in range(9)]
))


while not is_done:
    action = policy.predict(observation, t=10)  # always on off mode
    gravity_comp = calc_gravity(observation, inv_dyn=False)
    observation, reward, is_done, info = env.step(gravity_comp)
    t = info["time_index"]
    grasp_pts, normals = policy.compute_grasp_points_normals(observation, overwrite_z=True)
    if policy.set_mode(t) != last_mode:
        last_mode = policy.set_mode(t)
        if (~np.isclose(grasp_pts[:, 2], utils.CUBE_HALF_SIZE, atol=1e-6)).any():
            print(grasp_pts[:, 2] - utils.CUBE_HALF_SIZE)
            pdb.set_trace()
        markers = debug_markers(markers, grasp_pts)
        for m in markers.markers:
            print(m.position)
    if save_vid and t % save_freq == 0:
        write_frame_to_image(f"/tmp/img{t}.png", **camera_kwargs)

if save_vid:
    write_frames_to_video(img_dir="/tmp")

first choice face: 2
first choice face: 5
first choice face: 1
[2. 1. 5.]
assigning cp params for lifting
[array([0., 1., 0.]), array([ 0., -1.,  0.]), array([-1.,  0.,  0.])]
safe pos: [[ 0.     -0.0665  0.05  ]
 [ 0.      0.0665  0.05  ]
 [ 0.0665  0.      0.05  ]]
tip_positions: [[ 0.086       0.06105532  0.07906934]
 [ 0.00987546 -0.10500585  0.07906934]
 [-0.09587546  0.04395052  0.07906934]]
finger assignment: [0, 1, 2]
finger assignment by distance: [0, 1, 2]
['finger_middle_link_0', 'finger_lower_link_0', 'finger_tip_link_0']
['finger_middle_link_120', 'finger_lower_link_120', 'finger_tip_link_120']
['finger_middle_link_240', 'finger_lower_link_240', 'finger_tip_link_240']


AttributeError: 'PDControlPolicy' object has no attribute 'compute_grasp_points_normals'

## Moving fingertips up and down

In [19]:
# first write after reset
is_done = False
observation = env.reset()
p.resetDebugVisualizerCamera(**visualizer_kwargs)
t = 0
control_params = pos_control.load_config("pos_control.yaml")
kin = policy.kinematics

while not is_done:
    min_height, max_height = 0.035, 0.075
    h = np.sin(np.pi / 15 * t) * (max_height - min_height) + min_height
    tip_pos = np.asarray(
        policy.kinematics.forward_kinematics(
            observation["robot_observation"]["position"]
        )
    ).flatten()
    tip_pos[2::3] = h
    q, dq = observation['robot_observation']['position'], observation['robot_observation']['velocity']
    action = pos_control.get_joint_torques(tip_pos, kin.robot_model, kin.data,
                                            q, dq, control_params)
    # action = policy.position_pd_control(observation, tip_pos)
    action = policy.clip_to_space(action)
    observation, reward, is_done, info = env.step(action)


0.07633033039776284
0.07632707410668706
0.0763207641519427
0.07631158998900522
0.07629972877474014
0.07628534618300568
0.07626859716626613
0.07624962666671685
0.07622857028020685
0.07620555487604265
0.07618069917555965
0.0761541142921699
0.07612590423542064
0.07609616638143865
0.07606499191197887
0.07603246622416157
0.07599866931283625
0.07596367612739441
0.07592755690473077
0.07589037747993965
0.07585219957623301
0.07581308107546644
0.0757730762705696
0.07573223610109003
0.07569060837298315
0.07564823796370158
0.07560516701357073
0.07556143510437174
0.07551707942598956
0.07547213493192967
0.07542663448444922
0.07538060899000527
0.07533408752566606
0.07528709745709809
0.07523966454869131
0.07519181306635522
0.07514356587347427
0.07509494452048561
0.07504596932850796
0.07499665946741832
0.07494703302875433
0.07489710709378512
0.07484689779707937
0.07479642038587034
0.07474568927550153
0.0746947181012156
0.07464351976653197
0.07459210648844257
0.07454048983963855
0.07448868078796772
0.07

KeyboardInterrupt: 

## Running episode with PDControl Policy

In [7]:
# first write after reset
if save_vid:
    write_frame_to_image(f"/tmp/img{t}.png", **camera_kwargs)

markers = None
last_mode = ""

while not is_done:
    action = policy.predict(observation, t)  # always on off mode
    observation, reward, is_done, info = env.step(action)
    t = info["time_index"]
    grasp_pts, normals = policy.sample_grasp(observation, overwrite_z=True)
    if policy.set_mode(t) != last_mode:
        last_mode = policy.set_mode(t)
        if (~np.isclose(grasp_pts[:, 2], utils.CUBE_HALF_SIZE, atol=1e-6)).any():
            print(grasp_pts[:, 2] - utils.CUBE_HALF_SIZE)
            pdb.set_trace()
        markers = debug_markers(markers, grasp_pts)
    if save_vid and t % save_freq == 0:
        write_frame_to_image(f"/tmp/img{t}.png", **camera_kwargs)

if save_vid:
    write_frames_to_video(img_dir="/tmp")

first choice face: 2
first choice face: 5
first choice face: 1
[2. 1. 5.]
assigning cp params for lifting
[array([0., 1., 0.]), array([ 0., -1.,  0.]), array([-1.,  0.,  0.])]
first choice face: 2
first choice face: 5
first choice face: 1
[2. 1. 5.]
assigning cp params for lifting
[array([0., 1., 0.]), array([ 0., -1.,  0.]), array([-1.,  0.,  0.])]
first choice face: 2
first choice face: 5
first choice face: 1
[2. 1. 5.]
assigning cp params for lifting
[array([0., 1., 0.]), array([ 0., -1.,  0.]), array([-1.,  0.,  0.])]
first choice face: 2
first choice face: 5
first choice face: 1
[2. 1. 5.]
assigning cp params for lifting
[array([0., 1., 0.]), array([ 0., -1.,  0.]), array([-1.,  0.,  0.])]
first choice face: 2
first choice face: 5
first choice face: 1
[2. 1. 5.]
assigning cp params for lifting
[array([0., 1., 0.]), array([ 0., -1.,  0.]), array([-1.,  0.,  0.])]
first choice face: 2
first choice face: 5
first choice face: 1
[2. 1. 5.]
assigning cp params for lifting
[array([0., 1.

AssertionError: END OF EPISODE

In [48]:
grasp_pts[:, 2], utils.CUBE_HALF_SIZE

(array([0.0325, 0.0325, 0.0325]), 0.0335)

In [15]:
[p.getBodyInfo(x.body_id) for x in markers.markers]

[(b'link0', b''), (b'link0', b''), (b'link0', b'')]

In [38]:
import matplotlib.pyplot as plt

yzs = np.concatenate([gp[:, 1:] for gp in grasp_pt_hist])
xzs = np.concatenate([gp[:, [0,2]] for gp in grasp_pt_hist])

f, ax = plt.subplots(ncols=2, figsize=(12,6))
ax[0].scatter(yzs[:, 0], yzs[:, 1])
ax[1].scatter(xzs[:, 0], xzs[:, 1])

ValueError: need at least one array to concatenate

In [59]:
action

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
if save_vid:
    write_frames_to_video(frames)

wrote frames to vids/run0.mp4


In [44]:

Video("vids/run0.mp4")